spring.application.name=backend

# ===== Server =====
server.port=8085

# ===== PostgreSQL Database (Local) =====
# spring.datasource.url=jdbc:postgresql://localhost:5432/smartcampus
# spring.datasource.username=postgres
# spring.datasource.password=Sujani$2211
# spring.datasource.driver-class-name=org.postgresql.Driver

# ----- PostgreSQL (Supabase) -----
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/smartcampus?prepareThreshold=0
spring.datasource.username=postgres.pkspykytswumrkjevbrg
spring.datasource.password=StudentNo4200abc

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===== Connection Pool (HikariCP) =====
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# ===== Jackson (JSON formatting) =====
spring.jackson.serialization.indent-output=true

# ===== Logging =====
logging.level.org.springframework=INFO
logging.level.com.group137.smartcampus=DEBUG

# ===== JWT =====
app.jwt.secret=YXBwLWp3dC1zZWNyZXQta2V5LWhhc2gtdmFsdWUtZm9yLXNtYXJ0Y2FtcHVz
app.jwt.expiration-ms=86400000

# ===== Google OAuth2 (smartcampus-491519) =====
spring.security.oauth2.client.registration.google.client-id=803151720280-b7ise1kkpttm4kgc7s6t31qs06cr5hv3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# ===== CORS (React Frontend) =====
app.cors.allowed-origin-patterns=http://localhost:*,http://127.0.0.1:*
