spring.application.name=backend

# ----- PostgreSQL (Supabase) -----
spring.datasource.url=jdbc:postgresql://db.pkspykytswumrkjevbrg.supabase.co:5432/smartcampus
spring.datasource.username=postgres
spring.datasource.password=StudentNo4200abc
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== JWT =====
app.jwt.secret=YXBwLWp3dC1zZWNyZXQta2V5LWhhc2gtdmFsdWUtZm9yLXNtYXJ0Y2FtcHVz
app.jwt.expiration-ms=86400000

# ===== Google OAuth2 (smartcampus-491519) =====
spring.security.oauth2.client.registration.google.client-id=803151720280-b7ise1kkpttm4kgc7s6t31qs06cr5hv3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=email,profile

# ===== CORS =====
app.cors.allowed-origins=http://localhost:3000,http://localhost:3001

# ===== Server =====
server.port=8084
